function WelcomeLeave(Profile, Name, Text) {
    let themeList = [{
            "bi": "https://source.unsplash.com/LeG68PrXA6Y/500x500",
            "h": "500",
            "w": "500",
            "a.tp": "rect",
            "a.x": "250",
            "a.y": "250",
            "a.w": "393",
            "a.h": "225",
            "a.c": "#ffffff",
            "a.rx": "20",
            "a.ry": "20",
            "b.tp": "rect",
            "b.x": "250",
            "b.y": "305",
            "b.w": "393",
            "b.h": "1",
            "b.c": "#cccccc",
            "b.rx": "20",
            "b.ry": "20",
            "c.tp": "textbox",
            "c.x": "244",
            "c.y": "239",
            "c.w": "301",
            "c.h": "28",
            "c.t": "Welcome " + Name,
            "c.fs": "25",
            "c.lh": "1",
            "c.fw": "700",
            "c.ff": "Inter",
            "c.maxHeight": "25",
            "d.tp": "textbox",
            "d.x": "250",
            "d.y": "335",
            "d.w": "288",
            "d.h": "23",
            "d.c": "#555",
            "d.t": "Ok",
            "d.ta": "center",
            "d.fs": "20",
            "d.lh": "1",
            "d.fw": "400",
            "d.ff": "Inter",
            "d.maxHeight": "30",
            "e.tp": "image",
            "e.x": "115",
            "e.y": "190",
            "e.w": "128",
            "e.h": "128",
            "e.sx": "0.35",
            "e.sy": "0.35",
            "e.circleFrame": "true",
            "e.src": Profile,
            "f.tp": "textbox",
            "f.x": "244",
            "f.y": "271",
            "f.w": "301",
            "f.h": "23",
            "f.t": Text,
            "f.fs": "20",
            "f.lh": "1",
            "f.fw": "400",
            "f.ff": "Inter",
            "f.maxHeight": "20"
        },
        {
            "bg": "#ffffff",
            "h": "1200",
            "w": "1200",
            "a.tp": "textbox",
            "a.x": "599",
            "a.y": "645",
            "a.w": "1075",
            "a.h": "180",
            "a.c": "#000000",
            "a.t": Text,
            "a.fs": "48",
            "a.fw": "400",
            "a.ff": "Inter",
            "a.maxHeight": "656",
            "a.padding": "20",
            "b.tp": "textbox",
            "b.x": "191",
            "b.y": "443",
            "b.w": "454",
            "b.h": "40",
            "b.c": "#2f3338",
            "b.t": Name,
            "b.fs": "35",
            "b.cs": "80",
            "b.fw": "400",
            "b.ff": "Roboto",
            "b.ox": "left",
            "b.maxHeight": "40",
            "b.padding": "20",
            "c.tp": "textbox",
            "c.x": "191",
            "c.y": "483",
            "c.w": "238",
            "c.h": "34",
            "c.c": "#2f3338",
            "c.t": getCurrentTime(),
            "c.fs": "30",
            "c.fw": "400",
            "c.ff": "Open Sans",
            "c.ox": "left",
            "c.maxHeight": "26",
            "c.padding": "20",
            "d.tp": "image",
            "d.x": "57",
            "d.y": "461",
            "d.w": "400",
            "d.h": "400",
            "d.sx": "0.28",
            "d.sy": "0.28",
            "d.ox": "left",
            "d.rx": "200",
            "d.ry": "200",
            "d.src": Profile,
            "e.tp": "image",
            "e.x": "675",
            "e.y": "443",
            "e.w": "1200",
            "e.h": "1200",
            "e.sx": "0.03",
            "e.sy": "0.03",
            "e.src": "https://ucarecdn.com/c9a27f10-31ac-4660-9dc0-16ac8f374359//-/preview/-/quality/smart/"
        },
        {
            "bi": "https://source.unsplash.com/UF_wwDxI6uk/1200x630",
            "h": "630",
            "w": "1200",
            "a.tp": "rect",
            "a.x": "600",
            "a.y": "315",
            "a.w": "751",
            "a.h": "313",
            "a.c": "#ffffff",
            "a.rx": "20",
            "a.ry": "20",
            "b.tp": "textbox",
            "b.x": "594",
            "b.y": "306",
            "b.w": "603",
            "b.h": "45",
            "b.t": "Welcome " + Name,
            "b.fs": "40",
            "b.lh": "1",
            "b.fw": "400",
            "b.ff": "Inter",
            "b.oy": "top",
            "b.maxHeight": "40",
            "c.tp": "textbox",
            "c.x": "765",
            "c.y": "243",
            "c.w": "288",
            "c.h": "40",
            "c.c": "#555",
            "c.t": getCurrentTime(),
            "c.ta": "right",
            "c.fs": "35",
            "c.lh": "1",
            "c.fw": "400",
            "c.ff": "Inter",
            "c.maxHeight": "30",
            "d.tp": "textbox",
            "d.x": "600",
            "d.y": "397",
            "d.w": "613",
            "d.h": "34",
            "d.t": "Thanks for join",
            "d.fs": "30",
            "d.lh": "1",
            "d.fw": "400",
            "d.ff": "Inter",
            "d.maxHeight": "20",
            "e.tp": "image",
            "e.x": "324",
            "e.y": "245",
            "e.w": "128",
            "e.h": "128",
            "e.sx": "0.5",
            "e.sy": "0.5",
            "e.src": "https://logo.clearbit.com/twitter.com"
        },
        {
            "bi": "https://source.unsplash.com/eICUFSeirc0/1200x630",
            "bi.o": "NaN",
            "h": "630",
            "w": "1200",
            "a.tp": "rect",
            "a.ox": "center",
            "a.oy": "center",
            "a.x": "600",
            "a.y": "315",
            "a.w": "1024",
            "a.h": "380",
            "a.fill": "white",
            "a.sc": "gray",
            "a.o": "0.8",
            "a.rx": "20",
            "a.ry": "20",
            "b.tp": "textbox",
            "b.ox": "center",
            "b.oy": "center",
            "b.x": "600",
            "b.y": "388",
            "b.w": "905",
            "b.h": "149",
            "b.t": Text,
            "b.ta": "left",
            "b.fs": "44",
            "b.lh": "1",
            "b.fw": "400",
            "b.ff": "Inter",
            "b.fontStyle": "normal",
            "b.maxHeight": "150",
            "c.tp": "textbox",
            "c.ox": "center",
            "c.oy": "bottom",
            "c.x": "484",
            "c.y": "223",
            "c.w": "438",
            "c.h": "40",
            "c.fill": "#000000",
            "c.t": Name,
            "c.ta": "left",
            "c.fs": "35",
            "c.lh": "1",
            "c.fw": "400",
            "c.ff": "Poppins",
            "c.fontStyle": "normal",
            "c.maxHeight": "35",
            "d.tp": "image",
            "d.x": "147",
            "d.y": "181",
            "d.w": "400",
            "d.h": "400",
            "d.sx": "0.23",
            "d.sy": "0.23",
            "d.ox": "left",
            "d.oy": "top",
            "d.src": "https://unavatar.io/twitter/naval",
            "d.circleFrame": "true",
            "e.tp": "textbox",
            "e.ox": "center",
            "e.oy": "bottom",
            "e.x": "484",
            "e.y": "260",
            "e.w": "438",
            "e.h": "29",
            "e.fill": "#806b6b",
            "e.t": getCurrentTime(),
            "e.ta": "left",
            "e.fs": "26",
            "e.lh": "1",
            "e.fw": "400",
            "e.ff": "Open Sans",
            "e.fontStyle": "normal",
            "e.maxHeight": "26",
            "f.tp": "image",
            "f.x": "983",
            "f.y": "183",
            "f.w": "397",
            "f.h": "321",
            "f.sx": "0.2",
            "f.sy": "0.2",
            "f.ox": "left",
            "f.oy": "top",
            "f.src": "https://i.imgur.com/sT9QS7U.png"
        }
    ]

    let apiURL = 'https://img.bruzu.com/?' + new URLSearchParams(themeList[Math.floor(Math.random() * themeList.length)]).toString();
    return apiURL;
}

function getCurrentTime() {
    const options = {
        timeZone: 'Asia/Kolkata',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    };

    const now = new Date().toLocaleString('id-ID', options);
    return now;
}

export {
    WelcomeLeave
}

import {
    fileURLToPath,
    URL
} from 'url'
import chalk from 'chalk'
import fs from 'fs'
const __filename = new URL('', import.meta.url).pathname
const __dirname = new URL('.', import.meta.url).pathname
let file = fileURLToPath(import.meta.url)
fs.watchFile(file, () => {
    fs.unwatchFile(file)
    console.log(chalk.bgGreen(chalk.black("[  UPDATE ]")), chalk.white(`${__filename}`))
    import(`${file}?update=${Date.now()}`)
})